// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcFOHu-wp0GnwzWFZCzS-Miobij2QpbbQ',
    appId: '1:863944484000:web:2ec8110cd42e062b5715c5',
    messagingSenderId: '863944484000',
    projectId: 'square-ghost',
    authDomain: 'square-ghost.firebaseapp.com',
    storageBucket: 'square-ghost.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkt3VS_HmN4V34Rc82bf6jVnrWKfsJnpU',
    appId: '1:863944484000:android:b9a36306a38db4225715c5',
    messagingSenderId: '863944484000',
    projectId: 'square-ghost',
    storageBucket: 'square-ghost.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Xka7Pd-uJjE4tezKyRtmGU8nC6fbEB8',
    appId: '1:863944484000:ios:f744be85c721c4a05715c5',
    messagingSenderId: '863944484000',
    projectId: 'square-ghost',
    storageBucket: 'square-ghost.appspot.com',
    iosClientId: '863944484000-kqr1oe1chhnel9tlfpttm5umsvnpp359.apps.googleusercontent.com',
    iosBundleId: 'com.muj.squareghost.squareGhost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Xka7Pd-uJjE4tezKyRtmGU8nC6fbEB8',
    appId: '1:863944484000:ios:5fd3c50824dd33895715c5',
    messagingSenderId: '863944484000',
    projectId: 'square-ghost',
    storageBucket: 'square-ghost.appspot.com',
    iosClientId: '863944484000-kj4q1a9o4i91549onmekq455d9uoksms.apps.googleusercontent.com',
    iosBundleId: 'com.muj.squareghost.squareGhost.RunnerTests',
  );
}
