// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRUv551Hhb24sRCpdlIbydrSuk31P-ofc',
    appId: '1:389989520532:web:05bced116e2843468b5081',
    messagingSenderId: '389989520532',
    projectId: 'square-ghost-renew',
    authDomain: 'square-ghost-renew.firebaseapp.com',
    databaseURL: 'https://square-ghost-renew-default-rtdb.firebaseio.com',
    storageBucket: 'square-ghost-renew.appspot.com',
    measurementId: 'G-NKC5QBLNND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4aduQhNslG46xanjnToRM5XnDJbBByLY',
    appId: '1:389989520532:android:867fbf24d16d65318b5081',
    messagingSenderId: '389989520532',
    projectId: 'square-ghost-renew',
    databaseURL: 'https://square-ghost-renew-default-rtdb.firebaseio.com',
    storageBucket: 'square-ghost-renew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy6eHixEc5_H59eYOZqcKx1Robt8HWjFQ',
    appId: '1:389989520532:ios:566780c22de59ccc8b5081',
    messagingSenderId: '389989520532',
    projectId: 'square-ghost-renew',
    databaseURL: 'https://square-ghost-renew-default-rtdb.firebaseio.com',
    storageBucket: 'square-ghost-renew.appspot.com',
    iosClientId: '389989520532-ig0c6n0091jurp2levr72etq6moj5d13.apps.googleusercontent.com',
    iosBundleId: 'com.muj.squareghost.squareGhost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy6eHixEc5_H59eYOZqcKx1Robt8HWjFQ',
    appId: '1:389989520532:ios:51d63751a4acc2db8b5081',
    messagingSenderId: '389989520532',
    projectId: 'square-ghost-renew',
    databaseURL: 'https://square-ghost-renew-default-rtdb.firebaseio.com',
    storageBucket: 'square-ghost-renew.appspot.com',
    iosClientId: '389989520532-k5qj9veu0plcu5av824rorvenic10c18.apps.googleusercontent.com',
    iosBundleId: 'com.muj.squareghost.squareGhost.RunnerTests',
  );
}
